
project_id = "oqpwgxrqwbgchirnnejj"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
file_size_limit = "50MB"

[auth]
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://localhost:5173"]
jwt_expiry = 3600
enable_signup = true

[functions]
[functions.submit-answer]
verify_jwt = true
[functions.upload-summary]
verify_jwt = true
[functions.get-past-paper-help]
verify_jwt = true
